#!/bin/sh

bookmark="$(xclip -o)"
file="$HOME/personal/bookmarks.txt"

if grep -q "^$bookmark$" "$file";then
    notify-send "Oops Already bookmarked"
else

    notify-send "Bookmark Added " "$bookmark is saved to file."
    echo "$bookmark" >> "$file"
fi
