#!/bin/sh
notify-send "Starting the shutdown routine!"
rsync -urv --exclude '.git' ~/.scripts/ ~/.local/bin/
notify-send "Synced Scripts"
github-sync.sh
notify-send "Synced Github"
prompt "Do you want to shutdown?" "shutdown now"
